//
//  TableViewController.swift
//  Coins
//
//  Created by Adam on 7/21/17.
//  Copyright © 2017 Jacob Pashman. All rights reserved.
//

import UIKit

class Name {
    let nameTitle: String
    let nameDetail: String
    
    init(nameTitle: String, nameDetail: String) {
        self.nameTitle = nameTitle
        self.nameDetail = nameDetail
    }
    
    var titleFirstLetter: String {
        return String(self.nameTitle[self.nameTitle.startIndex]).uppercased()
    }
}

class TableViewController : UIViewController, UITableViewDelegate, UITableViewDataSource {
    @IBOutlet weak var tableView: UITableView?
    
    
    
    
    var names: [Name] = []
    
    var sortedFirstLetters: [String] = []
    var sections: [[Name]] = [[]]
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        let cell0 = Name(nameTitle: "Afghanistan", nameDetail: "+93")
        names.append (cell0)
        let cell1 = Name(nameTitle: "Aland Islands", nameDetail: "+358")
        names.append (cell1)
        let cell2 = Name(nameTitle: "Albania", nameDetail: "+355")
        names.append (cell2)
        let cell3 = Name(nameTitle: "Algeria", nameDetail: "+213")
        names.append (cell3)
        let cell4 = Name(nameTitle: "AmericanSamoa", nameDetail: "+1684")
        names.append (cell4)
        let cell5 = Name(nameTitle: "Andorra", nameDetail: "+376")
        names.append (cell5)
        let cell6 = Name(nameTitle: "Angola", nameDetail: "+244")
        names.append (cell6)
        let cell7 = Name(nameTitle: "Anguilla", nameDetail: "+1264")
        names.append (cell7)
        let cell8 = Name(nameTitle: "Antarctica", nameDetail: "+672")
        names.append (cell8)
        let cell9 = Name(nameTitle: "Antigua and Barbuda", nameDetail: "+1268")
        names.append (cell9)
        let cell10 = Name(nameTitle: "Argentina", nameDetail: "+54")
        names.append (cell10)
        let cell11 = Name(nameTitle: "Armenia", nameDetail: "+374")
        names.append (cell11)
        let cell12 = Name(nameTitle: "Aruba", nameDetail: "+297")
        names.append (cell12)
        let cell13 = Name(nameTitle: "Australia", nameDetail: "+61")
        names.append (cell13)
        let cell14 = Name(nameTitle: "Austria", nameDetail: "+43")
        names.append (cell14)
        let cell15 = Name(nameTitle: "Azerbaijan", nameDetail: "+994")
        names.append (cell15)
        let cell16 = Name(nameTitle: "Bahamas", nameDetail: "+1242")
        names.append (cell16)
        let cell17 = Name(nameTitle: "Bahrain", nameDetail: "+973")
        names.append (cell17)
        let cell18 = Name(nameTitle: "Bangladesh", nameDetail: "+880")
        names.append (cell18)
        let cell19 = Name(nameTitle: "Barbados", nameDetail: "+1246")
        names.append (cell19)
        let cell20 = Name(nameTitle: "Belarus", nameDetail: "+375")
        names.append (cell20)
        let cell21 = Name(nameTitle: "Belgium", nameDetail: "+32")
        names.append (cell21)
        let cell22 = Name(nameTitle: "Belize", nameDetail: "+501")
        names.append (cell22)
        let cell23 = Name(nameTitle: "Benin", nameDetail: "+229")
        names.append (cell23)
        let cell24 = Name(nameTitle: "Bermuda", nameDetail: "+1441")
        names.append (cell24)
        let cell25 = Name(nameTitle: "Bhutan", nameDetail: "+975")
        names.append (cell25)
        let cell26 = Name(nameTitle: "Bolivia, Plurinational State of bolivia", nameDetail: "+591")
        names.append (cell26)
        let cell27 = Name(nameTitle: "Bosnia and Herzegovina", nameDetail: "+387")
        names.append (cell27)
        let cell28 = Name(nameTitle: "Botswana", nameDetail: "+267")
        names.append (cell28)
        let cell29 = Name(nameTitle: "Brazil", nameDetail: "+55")
        names.append (cell29)
        let cell30 = Name(nameTitle: "British Indian Ocean Territory", nameDetail: "+246")
        names.append (cell30)
        let cell31 = Name(nameTitle: "Brunei Darussalam", nameDetail: "+673")
        names.append (cell31)
        let cell32 = Name(nameTitle: "Bulgaria", nameDetail: "+359")
        names.append (cell32)
        let cell33 = Name(nameTitle: "Burkina Faso", nameDetail: "+226")
        names.append (cell33)
        let cell34 = Name(nameTitle: "Burundi", nameDetail: "+257")
        names.append (cell34)
        let cell35 = Name(nameTitle: "Cambodia", nameDetail: "+855")
        names.append (cell35)
        let cell36 = Name(nameTitle: "Cameroon", nameDetail: "+237")
        names.append (cell36)
        let cell37 = Name(nameTitle: "Canada", nameDetail: "+1")
        names.append (cell37)
        let cell38 = Name(nameTitle: "Cape Verde", nameDetail: "+238")
        names.append (cell38)
        let cell39 = Name(nameTitle: "Cayman Islands", nameDetail: "+ 345")
        names.append (cell39)
        let cell40 = Name(nameTitle: "Central African Republic", nameDetail: "+236")
        names.append (cell40)
        let cell41 = Name(nameTitle: "Chad", nameDetail: "+235")
        names.append (cell41)
        let cell42 = Name(nameTitle: "Chile", nameDetail: "+56")
        names.append (cell42)
        let cell43 = Name(nameTitle: "China", nameDetail: "+86")
        names.append (cell43)
        let cell44 = Name(nameTitle: "Christmas Island", nameDetail: "+61")
        names.append (cell44)
        let cell45 = Name(nameTitle: "Cocos (Keeling) Islands", nameDetail: "+61")
        names.append (cell45)
        let cell46 = Name(nameTitle: "Colombia", nameDetail: "+57")
        names.append (cell46)
        let cell47 = Name(nameTitle: "Comoros", nameDetail: "+269")
        names.append (cell47)
        let cell48 = Name(nameTitle: "Congo", nameDetail: "+242")
        names.append (cell48)
        let cell49 = Name(nameTitle: "Congo, The Democratic Republic of the Congo", nameDetail: "+243")
        names.append (cell49)
        let cell50 = Name(nameTitle: "Cook Islands", nameDetail: "+682")
        names.append (cell50)
        let cell51 = Name(nameTitle: "Costa Rica", nameDetail: "+506")
        names.append (cell51)
        let cell52 = Name(nameTitle: "Cote d'Ivoire", nameDetail: "+225")
        names.append (cell52)
        let cell53 = Name(nameTitle: "Croatia", nameDetail: "+385")
        names.append (cell53)
        let cell54 = Name(nameTitle: "Cuba", nameDetail: "+53")
        names.append (cell54)
        let cell55 = Name(nameTitle: "Cyprus", nameDetail: "+357")
        names.append (cell55)
        let cell56 = Name(nameTitle: "Czech Republic", nameDetail: "+420")
        names.append (cell56)
        let cell57 = Name(nameTitle: "Denmark", nameDetail: "+45")
        names.append (cell57)
        let cell58 = Name(nameTitle: "Djibouti", nameDetail: "+253")
        names.append (cell58)
        let cell59 = Name(nameTitle: "Dominica", nameDetail: "+1767")
        names.append (cell59)
        let cell60 = Name(nameTitle: "Dominican Republic", nameDetail: "+1849")
        names.append (cell60)
        let cell61 = Name(nameTitle: "Ecuador", nameDetail: "+593")
        names.append (cell61)
        let cell62 = Name(nameTitle: "Egypt", nameDetail: "+20")
        names.append (cell62)
        let cell63 = Name(nameTitle: "El Salvador", nameDetail: "+503")
        names.append (cell63)
        let cell64 = Name(nameTitle: "Equatorial Guinea", nameDetail: "+240")
        names.append (cell64)
        let cell65 = Name(nameTitle: "Eritrea", nameDetail: "+291")
        names.append (cell65)
        let cell66 = Name(nameTitle: "Estonia", nameDetail: "+372")
        names.append (cell66)
        let cell67 = Name(nameTitle: "Ethiopia", nameDetail: "+251")
        names.append (cell67)
        let cell68 = Name(nameTitle: "Falkland Islands (Malvinas)", nameDetail: "+500")
        names.append (cell68)
        let cell69 = Name(nameTitle: "Faroe Islands", nameDetail: "+298")
        names.append (cell69)
        let cell70 = Name(nameTitle: "Fiji", nameDetail: "+679")
        names.append (cell70)
        let cell71 = Name(nameTitle: "Finland", nameDetail: "+358")
        names.append (cell71)
        let cell72 = Name(nameTitle: "France", nameDetail: "+33")
        names.append (cell72)
        let cell73 = Name(nameTitle: "French Guiana", nameDetail: "+594")
        names.append (cell73)
        let cell74 = Name(nameTitle: "French Polynesia", nameDetail: "+689")
        names.append (cell74)
        let cell75 = Name(nameTitle: "Gabon", nameDetail: "+241")
        names.append (cell75)
        let cell76 = Name(nameTitle: "Gambia", nameDetail: "+220")
        names.append (cell76)
        let cell77 = Name(nameTitle: "Georgia", nameDetail: "+995")
        names.append (cell77)
        let cell78 = Name(nameTitle: "Germany", nameDetail: "+49")
        names.append (cell78)
        let cell79 = Name(nameTitle: "Ghana", nameDetail: "+233")
        names.append (cell79)
        let cell80 = Name(nameTitle: "Gibraltar", nameDetail: "+350")
        names.append (cell80)
        let cell81 = Name(nameTitle: "Greece", nameDetail: "+30")
        names.append (cell81)
        let cell82 = Name(nameTitle: "Greenland", nameDetail: "+299")
        names.append (cell82)
        let cell83 = Name(nameTitle: "Grenada", nameDetail: "+1473")
        names.append (cell83)
        let cell84 = Name(nameTitle: "Guadeloupe", nameDetail: "+590")
        names.append (cell84)
        let cell85 = Name(nameTitle: "Guam", nameDetail: "+1671")
        names.append (cell85)
        let cell86 = Name(nameTitle: "Guatemala", nameDetail: "+502")
        names.append (cell86)
        let cell87 = Name(nameTitle: "Guernsey", nameDetail: "+44")
        names.append (cell87)
        let cell88 = Name(nameTitle: "Guinea", nameDetail: "+224")
        names.append (cell88)
        let cell89 = Name(nameTitle: "Guinea-Bissau", nameDetail: "+245")
        names.append (cell89)
        let cell90 = Name(nameTitle: "Guyana", nameDetail: "+592")
        names.append (cell90)
        let cell91 = Name(nameTitle: "Haiti", nameDetail: "+509")
        names.append (cell91)
        let cell92 = Name(nameTitle: "Holy See (Vatican City State)", nameDetail: "+379")
        names.append (cell92)
        let cell93 = Name(nameTitle: "Honduras", nameDetail: "+504")
        names.append (cell93)
        let cell94 = Name(nameTitle: "Hong Kong", nameDetail: "+852")
        names.append (cell94)
        let cell95 = Name(nameTitle: "Hungary", nameDetail: "+36")
        names.append (cell95)
        let cell96 = Name(nameTitle: "Iceland", nameDetail: "+354")
        names.append (cell96)
        let cell97 = Name(nameTitle: "India", nameDetail: "+91")
        names.append (cell97)
        let cell98 = Name(nameTitle: "Indonesia", nameDetail: "+62")
        names.append (cell98)
        let cell99 = Name(nameTitle: "Iran, Islamic Republic of Persian Gulf", nameDetail: "+98")
        names.append (cell99)
        let cell100 = Name(nameTitle: "Iraq", nameDetail: "+964")
        names.append (cell100)
        let cell101 = Name(nameTitle: "Ireland", nameDetail: "+353")
        names.append (cell101)
        let cell102 = Name(nameTitle: "Isle of Man", nameDetail: "+44")
        names.append (cell102)
        let cell103 = Name(nameTitle: "Israel", nameDetail: "+972")
        names.append (cell103)
        let cell104 = Name(nameTitle: "Italy", nameDetail: "+39")
        names.append (cell104)
        let cell105 = Name(nameTitle: "Jamaica", nameDetail: "+1876")
        names.append (cell105)
        let cell106 = Name(nameTitle: "Japan", nameDetail: "+81")
        names.append (cell106)
        let cell107 = Name(nameTitle: "Jersey", nameDetail: "+44")
        names.append (cell107)
        let cell108 = Name(nameTitle: "Jordan", nameDetail: "+962")
        names.append (cell108)
        let cell109 = Name(nameTitle: "Kazakhstan", nameDetail: "+7")
        names.append (cell109)
        let cell110 = Name(nameTitle: "Kenya", nameDetail: "+254")
        names.append (cell110)
        let cell111 = Name(nameTitle: "Kiribati", nameDetail: "+686")
        names.append (cell111)
        let cell112 = Name(nameTitle: "Korea, Democratic People's Republic of Korea", nameDetail: "+850")
        names.append (cell112)
        let cell113 = Name(nameTitle: "Korea, Republic of South Korea", nameDetail: "+82")
        names.append (cell113)
        let cell114 = Name(nameTitle: "Kuwait", nameDetail: "+965")
        names.append (cell114)
        let cell115 = Name(nameTitle: "Kyrgyzstan", nameDetail: "+996")
        names.append (cell115)
        let cell116 = Name(nameTitle: "Laos", nameDetail: "+856")
        names.append (cell116)
        let cell117 = Name(nameTitle: "Latvia", nameDetail: "+371")
        names.append (cell117)
        let cell118 = Name(nameTitle: "Lebanon", nameDetail: "+961")
        names.append (cell118)
        let cell119 = Name(nameTitle: "Lesotho", nameDetail: "+266")
        names.append (cell119)
        let cell120 = Name(nameTitle: "Liberia", nameDetail: "+231")
        names.append (cell120)
        let cell121 = Name(nameTitle: "Libyan Arab Jamahiriya", nameDetail: "+218")
        names.append (cell121)
        let cell122 = Name(nameTitle: "Liechtenstein", nameDetail: "+423")
        names.append (cell122)
        let cell123 = Name(nameTitle: "Lithuania", nameDetail: "+370")
        names.append (cell123)
        let cell124 = Name(nameTitle: "Luxembourg", nameDetail: "+352")
        names.append (cell124)
        let cell125 = Name(nameTitle: "Macao", nameDetail: "+853")
        names.append (cell125)
        let cell126 = Name(nameTitle: "Macedonia", nameDetail: "+389")
        names.append (cell126)
        let cell127 = Name(nameTitle: "Madagascar", nameDetail: "+261")
        names.append (cell127)
        let cell128 = Name(nameTitle: "Malawi", nameDetail: "+265")
        names.append (cell128)
        let cell129 = Name(nameTitle: "Malaysia", nameDetail: "+60")
        names.append (cell129)
        let cell130 = Name(nameTitle: "Maldives", nameDetail: "+960")
        names.append (cell130)
        let cell131 = Name(nameTitle: "Mali", nameDetail: "+223")
        names.append (cell131)
        let cell132 = Name(nameTitle: "Malta", nameDetail: "+356")
        names.append (cell132)
        let cell133 = Name(nameTitle: "Marshall Islands", nameDetail: "+692")
        names.append (cell133)
        let cell134 = Name(nameTitle: "Martinique", nameDetail: "+596")
        names.append (cell134)
        let cell135 = Name(nameTitle: "Mauritania", nameDetail: "+222")
        names.append (cell135)
        let cell136 = Name(nameTitle: "Mauritius", nameDetail: "+230")
        names.append (cell136)
        let cell137 = Name(nameTitle: "Mayotte", nameDetail: "+262")
        names.append (cell137)
        let cell138 = Name(nameTitle: "Mexico", nameDetail: "+52")
        names.append (cell138)
        let cell139 = Name(nameTitle: "Micronesia, Federated States of Micronesia", nameDetail: "+691")
        names.append (cell139)
        let cell140 = Name(nameTitle: "Moldova", nameDetail: "+373")
        names.append (cell140)
        let cell141 = Name(nameTitle: "Monaco", nameDetail: "+377")
        names.append (cell141)
        let cell142 = Name(nameTitle: "Mongolia", nameDetail: "+976")
        names.append (cell142)
        let cell143 = Name(nameTitle: "Montenegro", nameDetail: "+382")
        names.append (cell143)
        let cell144 = Name(nameTitle: "Montserrat", nameDetail: "+1664")
        names.append (cell144)
        let cell145 = Name(nameTitle: "Morocco", nameDetail: "+212")
        names.append (cell145)
        let cell146 = Name(nameTitle: "Mozambique", nameDetail: "+258")
        names.append (cell146)
        let cell147 = Name(nameTitle: "Myanmar", nameDetail: "+95")
        names.append (cell147)
        let cell148 = Name(nameTitle: "Namibia", nameDetail: "+264")
        names.append (cell148)
        let cell149 = Name(nameTitle: "Nauru", nameDetail: "+674")
        names.append (cell149)
        let cell150 = Name(nameTitle: "Nepal", nameDetail: "+977")
        names.append (cell150)
        let cell151 = Name(nameTitle: "Netherlands", nameDetail: "+31")
        names.append (cell151)
        let cell152 = Name(nameTitle: "Netherlands Antilles", nameDetail: "+599")
        names.append (cell152)
        let cell153 = Name(nameTitle: "New Caledonia", nameDetail: "+687")
        names.append (cell153)
        let cell154 = Name(nameTitle: "New Zealand", nameDetail: "+64")
        names.append (cell154)
        let cell155 = Name(nameTitle: "Nicaragua", nameDetail: "+505")
        names.append (cell155)
        let cell156 = Name(nameTitle: "Niger", nameDetail: "+227")
        names.append (cell156)
        let cell157 = Name(nameTitle: "Nigeria", nameDetail: "+234")
        names.append (cell157)
        let cell158 = Name(nameTitle: "Niue", nameDetail: "+683")
        names.append (cell158)
        let cell159 = Name(nameTitle: "Norfolk Island", nameDetail: "+672")
        names.append (cell159)
        let cell160 = Name(nameTitle: "Northern Mariana Islands", nameDetail: "+1670")
        names.append (cell160)
        let cell161 = Name(nameTitle: "Norway", nameDetail: "+47")
        names.append (cell161)
        let cell162 = Name(nameTitle: "Oman", nameDetail: "+968")
        names.append (cell162)
        let cell163 = Name(nameTitle: "Pakistan", nameDetail: "+92")
        names.append (cell163)
        let cell164 = Name(nameTitle: "Palau", nameDetail: "+680")
        names.append (cell164)
        let cell165 = Name(nameTitle: "Palestinian Territory, Occupied", nameDetail: "+970")
        names.append (cell165)
        let cell166 = Name(nameTitle: "Panama", nameDetail: "+507")
        names.append (cell166)
        let cell167 = Name(nameTitle: "Papua New Guinea", nameDetail: "+675")
        names.append (cell167)
        let cell168 = Name(nameTitle: "Paraguay", nameDetail: "+595")
        names.append (cell168)
        let cell169 = Name(nameTitle: "Peru", nameDetail: "+51")
        names.append (cell169)
        let cell170 = Name(nameTitle: "Philippines", nameDetail: "+63")
        names.append (cell170)
        let cell171 = Name(nameTitle: "Pitcairn", nameDetail: "+64")
        names.append (cell171)
        let cell172 = Name(nameTitle: "Poland", nameDetail: "+48")
        names.append (cell172)
        let cell173 = Name(nameTitle: "Portugal", nameDetail: "+351")
        names.append (cell173)
        let cell174 = Name(nameTitle: "Puerto Rico", nameDetail: "+1939")
        names.append (cell174)
        let cell175 = Name(nameTitle: "Qatar", nameDetail: "+974")
        names.append (cell175)
        let cell176 = Name(nameTitle: "Romania", nameDetail: "+40")
        names.append (cell176)
        let cell177 = Name(nameTitle: "Russia", nameDetail: "+7")
        names.append (cell177)
        let cell178 = Name(nameTitle: "Rwanda", nameDetail: "+250")
        names.append (cell178)
        let cell179 = Name(nameTitle: "Reunion", nameDetail: "+262")
        names.append (cell179)
        let cell180 = Name(nameTitle: "Saint Barthelemy", nameDetail: "+590")
        names.append (cell180)
        let cell181 = Name(nameTitle: "Saint Helena, Ascension and Tristan Da Cunha", nameDetail: "+290")
        names.append (cell181)
        let cell182 = Name(nameTitle: "Saint Kitts and Nevis", nameDetail: "+1869")
        names.append (cell182)
        let cell183 = Name(nameTitle: "Saint Lucia", nameDetail: "+1758")
        names.append (cell183)
        let cell184 = Name(nameTitle: "Saint Martin", nameDetail: "+590")
        names.append (cell184)
        let cell185 = Name(nameTitle: "Saint Pierre and Miquelon", nameDetail: "+508")
        names.append (cell185)
        let cell186 = Name(nameTitle: "Saint Vincent and the Grenadines", nameDetail: "+1784")
        names.append (cell186)
        let cell187 = Name(nameTitle: "Samoa", nameDetail: "+685")
        names.append (cell187)
        let cell188 = Name(nameTitle: "San Marino", nameDetail: "+378")
        names.append (cell188)
        let cell189 = Name(nameTitle: "Sao Tome and Principe", nameDetail: "+239")
        names.append (cell189)
        let cell190 = Name(nameTitle: "Saudi Arabia", nameDetail: "+966")
        names.append (cell190)
        let cell191 = Name(nameTitle: "Senegal", nameDetail: "+221")
        names.append (cell191)
        let cell192 = Name(nameTitle: "Serbia", nameDetail: "+381")
        names.append (cell192)
        let cell193 = Name(nameTitle: "Seychelles", nameDetail: "+248")
        names.append (cell193)
        let cell194 = Name(nameTitle: "Sierra Leone", nameDetail: "+232")
        names.append (cell194)
        let cell195 = Name(nameTitle: "Singapore", nameDetail: "+65")
        names.append (cell195)
        let cell196 = Name(nameTitle: "Slovakia", nameDetail: "+421")
        names.append (cell196)
        let cell197 = Name(nameTitle: "Slovenia", nameDetail: "+386")
        names.append (cell197)
        let cell198 = Name(nameTitle: "Solomon Islands", nameDetail: "+677")
        names.append (cell198)
        let cell199 = Name(nameTitle: "Somalia", nameDetail: "+252")
        names.append (cell199)
        let cell200 = Name(nameTitle: "South Africa", nameDetail: "+27")
        names.append (cell200)
        let cell201 = Name(nameTitle: "South Sudan", nameDetail: "+211")
        names.append (cell201)
        let cell202 = Name(nameTitle: "South Georgia and the South Sandwich Islands", nameDetail: "+500")
        names.append (cell202)
        let cell203 = Name(nameTitle: "Spain", nameDetail: "+34")
        names.append (cell203)
        let cell204 = Name(nameTitle: "Sri Lanka", nameDetail: "+94")
        names.append (cell204)
        let cell205 = Name(nameTitle: "Sudan", nameDetail: "+249")
        names.append (cell205)
        let cell206 = Name(nameTitle: "Suriname", nameDetail: "+597")
        names.append (cell206)
        let cell207 = Name(nameTitle: "Svalbard and Jan Mayen", nameDetail: "+47")
        names.append (cell207)
        let cell208 = Name(nameTitle: "Swaziland", nameDetail: "+268")
        names.append (cell208)
        let cell209 = Name(nameTitle: "Sweden", nameDetail: "+46")
        names.append (cell209)
        let cell210 = Name(nameTitle: "Switzerland", nameDetail: "+41")
        names.append (cell210)
        let cell211 = Name(nameTitle: "Syrian Arab Republic", nameDetail: "+963")
        names.append (cell211)
        let cell212 = Name(nameTitle: "Taiwan", nameDetail: "+886")
        names.append (cell212)
        let cell213 = Name(nameTitle: "Tajikistan", nameDetail: "+992")
        names.append (cell213)
        let cell214 = Name(nameTitle: "Tanzania, United Republic of Tanzania", nameDetail: "+255")
        names.append (cell214)
        let cell215 = Name(nameTitle: "Thailand", nameDetail: "+66")
        names.append (cell215)
        let cell216 = Name(nameTitle: "Timor-Leste", nameDetail: "+670")
        names.append (cell216)
        let cell217 = Name(nameTitle: "Togo", nameDetail: "+228")
        names.append (cell217)
        let cell218 = Name(nameTitle: "Tokelau", nameDetail: "+690")
        names.append (cell218)
        let cell219 = Name(nameTitle: "Tonga", nameDetail: "+676")
        names.append (cell219)
        let cell220 = Name(nameTitle: "Trinidad and Tobago", nameDetail: "+1868")
        names.append (cell220)
        let cell221 = Name(nameTitle: "Tunisia", nameDetail: "+216")
        names.append (cell221)
        let cell222 = Name(nameTitle: "Turkey", nameDetail: "+90")
        names.append (cell222)
        let cell223 = Name(nameTitle: "Turkmenistan", nameDetail: "+993")
        names.append (cell223)
        let cell224 = Name(nameTitle: "Turks and Caicos Islands", nameDetail: "+1649")
        names.append (cell224)
        let cell225 = Name(nameTitle: "Tuvalu", nameDetail: "+688")
        names.append (cell225)
        let cell226 = Name(nameTitle: "Uganda", nameDetail: "+256")
        names.append (cell226)
        let cell227 = Name(nameTitle: "Ukraine", nameDetail: "+380")
        names.append (cell227)
        let cell228 = Name(nameTitle: "United Arab Emirates", nameDetail: "+971")
        names.append (cell228)
        let cell229 = Name(nameTitle: "United Kingdom", nameDetail: "+44")
        names.append (cell229)
        let cell230 = Name(nameTitle: "United States", nameDetail: "+1")
        names.append (cell230)
        let cell231 = Name(nameTitle: "Uruguay", nameDetail: "+598")
        names.append (cell231)
        let cell232 = Name(nameTitle: "Uzbekistan", nameDetail: "+998")
        names.append (cell232)
        let cell233 = Name(nameTitle: "Vanuatu", nameDetail: "+678")
        names.append (cell233)
        let cell234 = Name(nameTitle: "Venezuela, Bolivarian Republic of Venezuela", nameDetail: "+58")
        names.append (cell234)
        let cell235 = Name(nameTitle: "Vietnam", nameDetail: "+84")
        names.append (cell235)
        let cell236 = Name(nameTitle: "Virgin Islands, British", nameDetail: "+1284")
        names.append (cell236)
        let cell237 = Name(nameTitle: "Virgin Islands, U.S.", nameDetail: "+1340")
        names.append (cell237)
        let cell238 = Name(nameTitle: "Wallis and Futuna", nameDetail: "+681")
        names.append (cell238)
        let cell239 = Name(nameTitle: "Yemen", nameDetail: "+967")
        names.append (cell239)
        let cell240 = Name(nameTitle: "Zambia", nameDetail: "+260")
        names.append (cell240)
        let cell241 = Name(nameTitle: "Zimbabwe", nameDetail: "+263")
        names.append (cell241)
        
        
        
        let firstLetters = names.map { $0.titleFirstLetter }
        let uniqueFirstLetters = Array(Set(firstLetters))
        
        sortedFirstLetters = uniqueFirstLetters.sorted()
        sections = sortedFirstLetters.map { firstLetter in
            return names
                .filter { $0.titleFirstLetter == firstLetter }
                .sorted { $0.nameTitle < $1.nameTitle }
        }
    }
    
    func tableView(_ tableView: UITableView, titleForHeaderInSection section: Int) -> String? {
        return sortedFirstLetters[section]
    }
    
    func sectionIndexTitles(for tableView: UITableView) -> [String]? {
        return sortedFirstLetters
    }
    
    func numberOfSections(in tableView: UITableView) -> Int {
        return sections.count
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return sections[section].count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let name = sections[indexPath.section][indexPath.row]
        
        let cell = UITableViewCell(style: .subtitle, reuseIdentifier: nil)
        cell.textLabel?.text = name.nameTitle
        cell.detailTextLabel?.text = name.nameDetail
        
        return cell
    }

    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        let indexPath = tableView.indexPathForSelectedRow //optional, to get from any UIButton for example
        
        let currentCell = tableView.cellForRow(at: indexPath!) as! UITableViewCell
        UserDefaults.standard.set(currentCell.textLabel!.text!, forKey: "selectedcell")
        performSegue(withIdentifier: "backtosignup", sender: Any?.self)
    }
    
}
