# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'Coin' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for Coin
    pod 'Alamofire', '~> 4.4'
    pod 'SwiftyJSON'
    pod 'Firebase/Auth'
    pod 'Firebase'
    pod 'Firebase/Database'
    pod 'Firebase/RemoteConfig'
    pod 'QRCode'
    pod 'SearchTextField'
    pod 'SwiftQRCode'
    pod 'PhoneNumberKit'
    pod 'SACountingLabel'
    pod 'Canvas'
    pod 'Firebase/Messaging'
    pod 'Spring', :git => 'https://github.com/MengTo/Spring.git', :branch => 'swift3'    
    target 'CoinTests' do
        inherit! :search_paths
        # Pods for testing
    end
    
    target 'CoinUITests' do
        inherit! :search_paths
        # Pods for testing
    end
    
end

