# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Coins' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for Coins
    pod 'Alamofire', '~> 4.4'
    pod 'SwiftyJSON'
    pod 'Firebase/Auth'
    pod 'Firebase'
    pod 'Firebase/Database'
    pod 'QRCode'
    target 'CoinsTests' do
        inherit! :search_paths
        # Pods for testing
    end
    
    target 'CoinsUITests' do
        inherit! :search_paths
        # Pods for testing
    end
    
end

