# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'Coins' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for Coins
    pod 'Alamofire', '~> 4.4'
    pod 'SwiftyJSON'
    pod 'Firebase/Auth'
    pod 'Firebase'
    pod 'Firebase/Database'
    pod 'QRCode'
    pod "SearchTextField"
    pod 'QRCodeReader.swift', '~> 7.4.3'
    pod 'SwiftQRCode'
    pod 'PhoneNumberKit'
    
    
    target 'CoinsTests' do
        inherit! :search_paths
        # Pods for testing
    end
    
    target 'CoinsUITests' do
        inherit! :search_paths
        # Pods for testing
    end
    
end

