-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgkALqVxwq0/qqr9MZCr5RULJxfluOVDXAfEXEdp9D7SygCgYIKoZIzj0DAQehRANCAAQyKG6ZZR2LyMQavvJn5ZFzXPLrdlMmHQCckZDlwh1JrxgM+iopIjPXsa/VUiuDr10CNJIFk8SfXCawpOOt5L6j
-----END PRIVATE KEY-----